<?php

namespace Hametuha\HamePub\Parser;


use Hametuha\HamePub\Definitions\Mime;
use Hametuha\HamePub\Pattern\Application;
use Masterminds\HTML5;

/**
 * Parse HTML
 *
 * @package Hametuha\HamePub\Parser
 */
class HTML5Parser extends Application
{

	/**
	 * @var HTML5
	 */
	protected $html5 = null;

	/**
	 * Constructor
	 *
	 * @param string $id
	 */
	protected function __construct( $id ) {
		parent::__construct( $id ); // TODO: Change the autogenerated stub
		$this->html5 = new HTML5();
	}


	/**
	 * Get HTML5 string
	 *
	 * @return string
	 */
	public function convertToString($dom){
		$html = $this->html5->saveHTML($dom);
		$html = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>'."\n".$html;
		// Library HTML5 always drop xmlns.
		$html = str_replace('<html', '<html xmlns="http://www.w3.org/1999/xhtml"', $html);
		return preg_replace('/<(meta|link|img)([^>]+)>/u', '<$1$2 />', $html);
	}

	/**
	 * Save Dom as XHTML file.
	 *
	 * @param \DOMDocument $dom
	 * @param string $name
	 *
	 * @return bool|string
	 */
	public function saveDom( \DOMDocument $dom, $name ){
		return $this->distributor->write($this->convertToString($dom), "OEBPS/Text/{$name}");
	}

	/**
	 * Extract assets
	 *
	 * @param \DomDocument $dom
	 * @param string $tag
	 * @param string $attr
	 * @param string $url_base
	 * @param string $doc_root
	 * @return array
	 */
	public function extractAssets(\DomDocument &$dom, $tag, $attr, $url_base, $doc_root ){
		$paths = [];
		foreach( $dom->getElementsByTagName($tag) as $elem ){
			list($value) = explode('?', $elem->getAttribute($attr));
			if( false !== strpos($value, $url_base) ){
				$path = str_replace($url_base, $doc_root, $value);
				if( file_exists($path) ){
					$dir = 'Asset';
					$new_path = ltrim(str_replace($doc_root, $dir, $path), DIRECTORY_SEPARATOR);
					$elem->setAttribute($attr, '../'.$new_path);
					if( $this->distributor->copy($path, 'OEBPS/'.$new_path) ){
						$paths[] = $new_path;
					}
				}
			}
		}
		return $paths;
	}

	/**
	 * Parse HTML5 and convert to Dom document
	 *
	 * @param $string
	 *
	 * @return false|\DomDocument
	 */
	public function parseFromString($string){
		$dom = $this->html5->loadHTML($string);
		if( is_a($dom, 'DOMDocument') ){
			return $dom;
		}else{
			return false;
		}
	}
}
