#!/usr/bin/env php
<?php
/**
 * Command line utility
 *
 * @package Hametuha\HamePub
 */
if( 'cli' !== php_sapi_name() ){
    die('This is command line tool.');
}

// Load auto loader
require_once __DIR__. '/vendor/autoload.php';

// Init Boris
$boris = new \Boris\Boris('hamepub> ');
$config = new \Boris\Config();
$config->apply($boris);

$options = new \Boris\CLIOptionsHandler();
$options->handle($boris);

// Set variables
$boris->setLocal([
    'epub_id' => 10,
    'temp_dir' => __DIR__.DIRECTORY_SEPARATOR.'tests'.DIRECTORY_SEPARATOR.'tmp',
]);

// Start
$boris->start();
